services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:vnext-preview
    ports:
      - "8081:8081"
      - "1234:1234"
    environment:
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=false
      - PROTOCOL=https
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:8081/_explorer/emulator.pem"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
